#!/usr/bin/env bash

# DELETE THE CLOUDUNIT CUSTOM BLOCK
sed -i '/#CLOUDUNIT_START/,/#CLOUDUNIT_END/d' $JBOSS_HOME/bin/standalone.conf

STRING_TO_INCLUDE_WITHOUT_INTERPRETATION='$JAVA_OPTS'

# ADD A CLOUDUNIT CUSTOM BLOCK WITH THE OPTION
echo "#CLOUDUNIT_START" >> $JBOSS_HOME/bin/standalone.conf
echo "JAVA_OPTS=\"$STRING_TO_INCLUDE_WITHOUT_INTERPRETATION $1 \"" >> $JBOSS_HOME/bin/standalone.conf
echo "#CLOUDUNIT_END" >> $JBOSS_HOME/bin/standalone.conf

exit 0


